Fix LuigiConfigParser for Python3 (#12)
## Description
In python 3, the default section (usually `'DEFAULT'`) is special cased. As in python 2, `ConfigParser.has_section(self, section)` will return False. But, it actually does exist and `add_section` will throw an exception (in python2, this does not cause an exception to be thrown).

To manage this, we need to check if the section we're trying to add is the default section, and skip trying to add it if so.

## Motivation and Context
A portion of our unit tests are currently failing due to this bug. 

## Have you tested this? If so, how?
In the foursquare.web repo, I ran:
```
./python -3 -m pip install -e ../luigi
./python -3 
Python 3.9.12 (main, Jul 27 2023, 12:56:03) 
Type 'copyright', 'credits' or 'license' for more information
IPython 8.3.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from luigi.configuration import LuigiConfigParser

In [2]: l = LuigiConfigParser({"env": "test"})

In [3]: l.set("test", "test", "test")

In [4]: l.get("test", "test")
Out[4]: 'test'

In [5]: l.sections()
Out[5]: ['test']

In [6]: l.defaults()
Out[6]: {'env': 'test'}

In [7]: 
```

With our current version (+fs12):
```
./python -3 -m pip freeze | grep luigi
luigi==2.7.8+fs12
./python -3                           
Python 3.9.12 (main, Jul 27 2023, 12:56:03) 
Type 'copyright', 'credits' or 'license' for more information
IPython 8.3.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from luigi.configuration import LuigiConfigParser

In [2]: l = LuigiConfigParser({"env": "test"})
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[snip]
ValueError: Invalid section name: 'DEFAULT'
```